keys:
  - &bbigras age1ejjym658kp46e5jfqm2mplh895caekll9lpgmy9xgtgu0mh97y2qw09zpp
  - &desktop age1tjnr7305we8aa88kespe0awvntfvy6lsvcptrzzpgqq0eswnrvsskgq757
  - &laptop 044563484de3f8a04eab2fa2a1f1884c176b12c3
  - &work age10npkltghhgu7yytefxtwtevwwgsguxn0fr4rr4x7pv5ts08c8s5sydd3aj

creation_rules:
  - path_regex: hosts/desktop/restic-desktop.yaml
    key_groups:
      - age:
        - *desktop
        - *bbigras
  - path_regex: hosts/laptop/restic-laptop.yaml
    key_groups:
      - pgp:
        - *laptop
      - age:
        - *bbigras
  - path_regex: hosts/work/secrets.yaml
    key_groups:
      - age:
        - *work
        - *bbigras
