keys:
  - &bbigras age1ejjym658kp46e5jfqm2mplh895caekll9lpgmy9xgtgu0mh97y2qw09zpp
  - &desktop age1l89jtqe6l80qj22ecrvs6sgmc3kx3d5w3m69a5h0frnrxmrajf8qj99m6x
  - &laptop age1nhneswdxmkzwmlz9n9r7ee4ermv56dzs3kc624xgu3rtec9pcd4q4g9r6r
  - &work age10npkltghhgu7yytefxtwtevwwgsguxn0fr4rr4x7pv5ts08c8s5sydd3aj

creation_rules:
  - path_regex: hosts/desktop/restic-desktop.yaml
    key_groups:
      - age:
        - *desktop
        - *bbigras
  - path_regex: hosts/laptop/secrets.yaml
    key_groups:
      - age:
        - *bbigras
        - *laptop
  - path_regex: hosts/work/secrets.yaml
    key_groups:
      - age:
        - *work
        - *bbigras
