name: "Setup Nix"
description: "Sets up Nix, Cachix, and remote builders"

inputs:
  cachix:
    description: "Whether to setup cachix"
    required: true
    default: true
    type: boolean
  cachix-auth-token:
    description: "Auth token for cachix"
    required: false
  cachix-signing-key:
    description: "Signing key for cachix"
    required: false
  github-token:
    description: "A GitHub token for making authenticated requests"
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@v2
      with:
        nix-package-url: "https://nix-config.cachix.org/serve/j26m73q2svl04nmvxksjwwns4rgb8x4w/nix-2.13.3-x86_64-linux.tar.xz"
        extra-conf: |
          always-allow-substitutes = true
          builders-use-substitutes = true
          experimental-features = nix-command flakes recursive-nix
        github-token: ${{ inputs.github-token }}
    - uses: cachix/cachix-action@v12
      if: ${{ inputs.cachix == 'true' }}
      with:
        name: bbigras-nix-config
        signingKey: ${{ inputs.cachix-signing-key }}
