name: "Setup Nix"
description: "Sets up Nix, Cachix, and remote builders"

inputs:
  cachix:
    description: "Whether to setup cachix"
    required: true
    default: true
    type: boolean
  cachix-auth-token:
    description: "Auth token for cachix"
    required: false
  cachix-signing-key:
    description: "Signing key for cachix"
    required: false
  github-token:
    description: "A GitHub token for making authenticated requests"
    default: ${{ github.token }}
  nix-package-url:
    description: "The Nix package to install"
    required: false

runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@v3
      with:
        nix-installer-tag: "v0.9.1"
        nix-package-url: ${{ inputs.nix-package-url }}
        extra-conf: |
          accept-flake-config = true
          builders-use-substitutes = true
          experimental-features = nix-command flakes
          extra-platforms = aarch64-linux
        github-token: ${{ inputs.github-token }}
    - uses: cachix/cachix-action@v12
      if: ${{ inputs.cachix == 'true' }}
      with:
        name: bbigras-nix-config
        signingKey: ${{ inputs.cachix-signing-key }}
        extraPullNames: "dendrite-demo-pinecone,nix-community,nix-on-droid,pre-commit-hooks,nix-config"
