{
  "name": "CI",
  "on": [
    "pull_request",
    "push"
  ],
  "jobs": {
    "build": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Checkout",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Make more space",
          "run": "sudo rm -rf /opt /usr/local || true &"
        },
        {
          "name": "Nix",
          "uses": "cachix/install-nix-action@v10",
          "with": {
            "skip_adding_nixpkgs_channel": true
          }
        },
        {
          "name": "Cachix",
          "uses": "cachix/cachix-action@v6",
          "with": {
            "name": "bbigras-nix-config",
            "signingKey": "'${{ secrets.CACHIX_SIGNING_KEY }}'"
          }
        },
        {
          "name": "add extra cachix caches",
          "run": "cachix use nix-community; cachix use nix-matrix-yggdrasil; cachix use eigenvalue; cachix use srid"
        },
        {
          "name": "Build",
          "run": "nix run '((import (import ./nix/sources.nix).nixpkgs {}).nix-build-uncached)' -c nix-build-uncached"
        }
      ]
    }
  }
}
