name: CI
on:
  push:
    branches:
      - master
      - flake-update
      - matrix
jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
          extra_nix_config: "experimental-features = nix-command flakes"
      - name: lints
        run: |
          nix develop -c pre-commit run --all-files --show-diff-on-failure --color=always || exit 1

  get-hosts:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-hosts.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
          extra_nix_config: "experimental-features = nix-command flakes"
      - id: get-hosts
        run: |
          echo "::set-output name=matrix::$(nix eval --json .#deploy.nodes | jq -c '{ host: keys }')"

  build-host:
    runs-on: ubuntu-latest
    needs: get-hosts
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-hosts.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
          extra_nix_config: "experimental-features = nix-command flakes"
      - uses: cachix/cachix-action@v8
        with:
          name: bbigras-nix-config
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - name: add extra cachix caches
        run: |
          nix develop -c cachix use nix-community \
          nix develop -c cachix use eigenvalue \
          nix develop -c cachix use mjlbach
      - name: nix-build
        run: |
          nix run nixpkgs#nix-build-uncached -- \
            -E "(builtins.getFlake (toString ./.)).deploy.nodes.${{ matrix.host }}.profiles.system.path"

  check-flake:
    runs-on: ubuntu-latest
    needs: build-host
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
          extra_nix_config: "experimental-features = nix-command flakes"
      - uses: cachix/cachix-action@v8
        with:
          name: bbigras-nix-config
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: add extra cachix caches
        run: |
          nix develop -c cachix use nix-community \
          nix develop -c cachix use eigenvalue \
          nix develop -c cachix use mjlbach
      - name: check-flake
        run: "nix flake check"
