name: update flakes
on:
  schedule:
    # every day at 8am UTC
    - cron:  '0 8 * * *'
  workflow_dispatch:
jobs:
  update-flakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            # Nix Flakes doesn't work on shallow clones
            fetch-depth: 0
      - run: sudo rm -rf /opt /usr/local || true &
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
          extra_nix_config: "experimental-features = nix-command flakes"
      - uses: cachix/cachix-action@v8
        with:
          name: bbigras-nix-config
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: cachix use nix-community; cachix use nix-matrix-yggdrasil; cachix use eigenvalue; cachix use mjlbach; cachix use pre-commit-hooks
      - run: git config --global user.email "noreply@github.com"
      - run: git config --global user.name "GitHub"
      - run: nix flake update --impure --recreate-lock-file --commit-lock-file
      - run: nix develop -c nix-build-uncached ci.nix
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "[automation] update flakes dependencies"
          title: "flake: update"
          branch: "flake-update"
          delete-branch: true
